### ISSUE TITLE
[BUG]  - Timeout Error on play stream in parallel internal test.

### ISSUE THREAD

**Issue by jdrzaszcz** [thesofproject/sof#1771]
**Describe the bug**
Timeout error In parallel internal test when trying to start plb_stream on second SSP.
IPC Timeout after sending StreamTrigStart.
This also happens in the demux test.

Sending StreamTrigStart (60040000, 00000000)
Payload:
0000000C 60040000 00000008 
FW status on IPC timeout: 0x00000005 0x00000000 0x00004000
Waiting for IPC notifications to drain

Occurs after this commit:
53529b103d071128f3e2620012eb00066c0fc5ee

### Start playback and capture streams for SSP2 (0) ###
DSP is not functional. Skipping sending IPC: StreamTrigStart (60040000, 00000000)
Payload:
0000000C 60040000 00000014 
DSP is not functional. Skipping sending IPC: StreamTrigStart (60040000, 00000000)
Payload:
0000000C 60040000 00000010 

### Wait for the end of the playback streams (0) ###
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\test_logger.py", line 563, in wrapper
    returned = method(self, *args, **kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\hda_streamer.py", line 315, in _thread
    sec=self.stream_hang_timeout))
TimeoutError: Capture stream not running for 1 seconds

Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\test_logger.py", line 563, in wrapper
    returned = method(self, *args, **kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\hda_streamer.py", line 226, in _thread
    sec=self.stream_hang_timeout))
TimeoutError: Play stream not running for 1 seconds

Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\lab_audiodsp\AppData\Local\Continuum\miniconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\test_logger.py", line 563, in wrapper
    returned = method(self, *args, **kwargs)
  File "C:\work\JD\cavs_scripts-py\utilities\hda_streamer.py", line 315, in _thread
    sec=self.stream_hang_timeout))
TimeoutError: Capture stream not running for 1 seconds

**To Reproduce**
Platform
WHL RVP
master branch

Run test_01_ptp_parallel_internal.py or test_01_demux_simple.py
from https://gitlab.devtools.intel.com/cavs_scripts-py/cavs_scripts-py repository.

**Reproduction Rate**
100%

**Expected behavior**
Captured files on three SSP loopback with 3 second recording time.

example log file:
[parallel_internal.log](https://github.com/thesofproject/sof/files/3550416/parallel_internal.log)

**Comment by lgirdwood** [comment]
@tlauda Seems the related to https://github.com/thesofproject/sof/issues/1762

**Comment by tlauda** [comment]
@jdrzaszcz @lgirdwood Should be fixed with #1850.
