### ISSUE TITLE
[BUG][Fuzzing]Testbench: Segmentation Fault: when running testbench with a topology file

### ISSUE THREAD

**Issue by ymdatta** [thesofproject/sof#3222]
**Describe the bug**
This bug was found when fuzzing the testbench using AFL fuzzer. For a fuzzed topology file input (i.e this topology was generated by the fuzzer) testbench exits with segmentation fault(core dumped) error.

**To Reproduce**
1. Build the testbench from the using `host-build-all.sh` script from scripts directory.
2. Download the topology file from [here](https://github.com/ymdatta/sof_testbench_fuzz_files/blob/master/id_02_tplg.bin).
3. Run the `host-testbench.sh` script from scripts directory to see if testbench works.
4. Run the following command:

```   
./tools/testbench/build_testbench/install/bin/testbench -r 48000 -R 48000 -i ./tools/test/audio/zeros_in.raw -o ./tools/testbench/build_testbench/volume_out.raw -t ./id_02_tplg.bin -b S16_LE
```

**Reproduction Rate**
All the time.

**Expected behavior**
If there is something wrong with topology file, the testbench should exit with some error code.

**Screenshots or console output**
1. Segmentation fault.

```
root@6989df4e5359:/home/sof/work/sof.git# ./tools/testbench/build_testbench/install/bin/testbench -r 48000 -R 48000 -i ./tools/test/audio/zeros_in.raw -o ./tools/testbench/build_testbench/volum
e_out.raw -t ./id_02_tplg.bin -b S16_LE
unknown ipc_init()
unknown edf_scheduler_init()
debug: loading widget PCM0P id 11
Segmentation fault (core dumped)
```

2. gdb trace log

```
(gdb) r -r 48000 -R 48000 -i ./tools/test/audio/zeros_in.raw -o ./tools/testbench/build_testbench/volume_out.raw -t ./id_02_tplg.bin -b S16_LE
Starting program: /home/sof/work/sof.git/tools/testbench/build_testbench/install/bin/testbench -r 48000 -R 48000 -i ./tools/test/audio/zeros_in.raw -o ./tools/testbench/build_testbench/volume_o
ut.raw -t ./id_02_tplg.bin -b S16_LE
unknown ipc_init()
unknown edf_scheduler_init()
debug: loading widget PCM0P id 11

Program received signal SIGSEGV, Segmentation fault.
sof_parse_word_tokens (object=object@entry=0x7fffffffdebc, tokens=tokens@entry=0x55555576ca80 <comp_tokens>, count=count@entry=3, array=array@entry=0x555555770f30)
    at /home/sof/work/sof.git/tools/tplg_parser/tplg_parser.c:1315
1315                            if (tokens[j].token != elem->token)
(gdb) bt
#0  sof_parse_word_tokens (object=object@entry=0x7fffffffdebc, tokens=tokens@entry=0x55555576ca80 <comp_tokens>, count=count@entry=3, array=array@entry=0x555555770f30)
    at /home/sof/work/sof.git/tools/tplg_parser/tplg_parser.c:1315
#1  0x00007ffff740afb9 in sof_parse_tokens (object=object@entry=0x7fffffffdebc, tokens=tokens@entry=0x55555576ca80 <comp_tokens>, count=count@entry=3, array=array@entry=0x555555770f30, 
    priv_size=0) at /home/sof/work/sof.git/tools/tplg_parser/tplg_parser.c:1283
#2  0x0000555555563d72 in tplg_load_fileread (fileread=0x7fffffffdea0, size=164, pipeline_id=1, comp_id=0) at /home/sof/work/sof.git/tools/testbench/topology.c:189
#3  load_fileread (dev=0x55555576d8e0 <sof>, comp_id=0, pipeline_id=1, widget=0x555555770a70, dir=0, tp=0x7fffffffe190) at /home/sof/work/sof.git/tools/testbench/topology.c:281
#4  0x0000555555564c8d in load_aif_in_out (dev=dev@entry=0x55555576d8e0 <sof>, comp_id=comp_id@entry=0, pipeline_id=pipeline_id@entry=1, widget=widget@entry=0x555555770a70, dir=dir@entry=0, 
    tp=tp@entry=0x7fffffffe190) at /home/sof/work/sof.git/tools/testbench/topology.c:363
#5  0x00007ffff7407828 in load_widget (dev=dev@entry=0x55555576d8e0 <sof>, dev_type=dev_type@entry=1, temp_comp_list=temp_comp_list@entry=0x5555557709d0, comp_id=0, 
    comp_index=<optimized out>, pipeline_id=1, tp=0x7fffffffe190, sched_id=0x7fffffffe1c4, file=0x55555576f760) at /home/sof/work/sof.git/tools/tplg_parser/tplg_parser.c:1154
#6  0x000055555556770c in parse_topology (sof=0x55555576d8e0 <sof>, library_table=<optimized out>, tp=0x7fffffffe190, pipeline_msg=0x7fffffffe1d0 "\230\352\377\367\377\177")
    at /home/sof/work/sof.git/tools/testbench/topology.c:741
#7  0x000055555555709f in main (argc=<optimized out>, argv=<optimized out>) at /home/sof/work/sof.git/tools/testbench/testbench.c:226
```

**Comment by cujomalainey** [comment]
We have no codeowners for tplg_parser, @ranj063, @xiulipan and @singalsu look like closest owners.

**Comment by lgirdwood** [comment]
> We have no codeowners for tplg_parser, @ranj063, @xiulipan and @singalsu look like closest owners.

Ack - we should add some owners to CODEOWNERS. 
@ymdatta could our array index be too large ? (and does it come from topology ?)

**Comment by ymdatta** [comment]
@lgirdwood: Yes, i think index size is too large. 

If you take a look at this [line](https://github.com/thesofproject/sof/blob/master/tools/tplg_parser/tplg_parser.c#L1305) from the ```tplg_parser.c```, the value of  ```array->num_elems``` was  ```826361680``` when checked via gdb. With this, i came to the above conclusion that index size is too large.

Yes, the array comes from the topology file. This can be be confirmed from this [line](https://github.com/thesofproject/sof/blob/master/tools/testbench/topology.c#L178).

**Comment by singalsu** [comment]
Thanks for reporting! I think I can fix this.

**Comment by singalsu** [comment]
I created PR #3246 . It returns now an error for the fuzzed topology.

```
./tools/testbench/build_testbench/install/bin/testbench -r 48000 -R 48000 -i ./tools/test/audio/zeros_in.raw -o ./tools/testbench/build_testbench/volume_out.raw -t ./id_02_tplg.bin -b S16_LE
unknown ipc_init()
unknown edf_scheduler_init()
debug: loading widget PCM0P id 11
error: illegal array number of elements 826361680
error: parse comp tokens 164
error: load AIF IN failed
error: loading widget
error: parsing topology
```

**Comment by cujomalainey** [comment]
Fixed
