### ISSUE TITLE
[BUG] keyword detection: Exception: Zero marker not found / failed to alloc 0x12500 bytes

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/sof#5363]
For the last 3 months the same check-keyword-detection test has been failing the same every day on the same platform:

```
Max peak (3200 samples): 0x00001e5e #####                23%
Max peak (3200 samples): 0x00001e5e #####                23%
Max peak (3200 samples): 0x00001e5e #####                23%
Max peak (3200 samples): 0x00001e5e #####                23%
Max peak (1280 samples): 0x00001e5e #####                23%
Traceback (most recent call last):
  File "/home/ubuntu/sof-test/tools/wavetool.py", line 266, in 
    main()
  File "/home/ubuntu/sof-test/tools/wavetool.py", line 263, in main
    do_wave_analysis()
  File "/home/ubuntu/sof-test/tools/wavetool.py", line 114, in do_wave_analysis
    analyze_wav_wov(wave, fs_wav)
  File "/home/ubuntu/sof-test/tools/wavetool.py", line 190, in analyze_wav_wov
    marker_start, marker_end = find_zero_marker(trimmed_wave[:,0], 0)
  File "/home/ubuntu/sof-test/tools/wavetool.py", line 166, in find_zero_marker
    raise Exception('Zero marker not found')
Exception: Zero marker not found
```
```
[          55.729164] (          13.802083) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12500 bytes zone 0x3 caps 0x8 flags 0x0
[          69.531247] (          13.802083) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12400 bytes zone 0x3 caps 0x8 flags 0x0
[          83.437497] (          13.906249) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12300 bytes zone 0x3 caps 0x8 flags 0x0
[          97.239579] (          13.802083) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12200 bytes zone 0x3 caps 0x8 flags 0x0
[         111.041662] (          13.802083) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12100 bytes zone 0x3 caps 0x8 flags 0x0
[         124.947912] (          13.906249) c0 dma-trace                   src/lib/alloc.c:958  ERROR failed to alloc 0x12000 bytes zone 0x3 caps 0x8 flags 0x0
```

Other systems never run that test, so the failure may not be ADL specific.

First such failure on the 24th November 2021 in 8428?model=ADLP_RVP_HDA&testcase=check-keyword-detection

Start Time: 2021-11-24 03:01:08 UTC
Kernel Branch: topic/sof-dev
Kernel Commit: 76583781
SOF Branch: main
SOF Commit: d959089d8e28
Zephyr Commit: a60317167bdd
sof-test: 0a464ff 

In the 5 previous daily runs 8329, 8350, 8364, 8393, 8417 3 months ago, the same test failed but in a very different way:
```
THD+N of low volume sine wave: [-65.59282139 -66.77905254] dB
THD+N of high volume sine wave: [-54.51469332 -56.425343  ] dB
THD+N too high, wave analysis result: FAILED
```
At the time this error was tracked by internal issue number 14 "upgrade ADC on DMIC injector to avoid keyword detection case failure"

Dairy 8417 was:
Start Time: 2021-11-23 21:23:10 UTC
Kernel Branch: topic/sof-dev
Kernel Commit: d5c4c30a
SOF Branch: main
SOF Commit: d959089d8e28
sof-test: 0a464ff 

Most recent failure: 10146?model=ADLP_RVP_HDA&testcase=check-keyword-detection
Start Time: 2022-02-11 22:27:26 UTC
Kernel Branch: topic/sof-dev
Kernel Commit: 98119478
SOF Branch: main
SOF Commit: b8954754f055

I found this error 90 times between 8428 and 10146 included, so it's likely been happening on every daily run.

Also spotted twice with some once-off TGLU_RVP_HDA testing 8322?model=TGLU_RVP_HDA&testcase=check-keyword-detection + 8327

Start Time: 2021-11-19 04:36:04 UTC
Kernel Branch: topic/sof-dev
Kernel Commit: 2a6679fb
SOF Branch: main
SOF Commit: 8e7c07dd00ff

**Comment by marc-hb** [comment]
P1 because daily tests are failing. If lower priority then please say so and I'll SKIP it.
