### ISSUE TITLE
[BUG] Build fail on mt8186/v0.2 if using newest alsa-lib

### ISSUE THREAD

**Issue by Zames-Chang** [thesofproject/sof#6667]
**Describe the bug**
If you use newest alsa-lib to build topology will causing build failure.
It can be workaround by checkout alsa-lib to commit 152983f01b0bc1178ea0d461ebf66e2d2a8e2e02

**To Reproduce**
git checkout mt8186/v0.2
./scripts/build-tools.sh -T

**Reproduction Rate**
100%

**Expected behavior**
Can build

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: N/A
    * SOF: d3d49dce58d3d316cd7044ee84996e48b1457df4
2) Name of the topology file
    * Topology: I build all tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: mt8186

**Screenshots or console output**
```
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- No CMAKE_BUILD_TYPE, defaulting to Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /sof/sof/tools/build_tools
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'glib-2.0'
-- Configuring done
-- Generating done
-- Build files have been written to: /sof/sof/tools/build_tools/fuzzer
+ cmake --build /sof/sof/tools/build_tools -- -j 128 topologies
[  0%] Generating sof-mtl-nocodec.tplg
[  0%] Generating cavs-mixin-mixout-hda-2ch-cnl.tplg
[  0%] Generating cavs-mixin-mixout-hda-2ch-tgl.tplg
[  0%] Generating cavs-mixin-mixout-hda-4ch-tgl.tplg
[  1%] Generating cavs-mixin-mixout-hda-4ch-cnl.tplg
[  1%] Generating cavs-mixin-mixout-hda.tplg
[  1%] Generating cavs-passthrough-hdmi.tplg
[  1%] Generating cavs-tgl-nocodec.tplg
[  1%] Generating cavs-sdw.tplg
find_modes(): fs not set
find_modes(): fs not set
find_modes(): fs not set
saving nhlt as binary in nhlt-ace-mtl-nocodec.bin
find_modes(): fs not set
saving nhlt as binary in nhlt.bin
saving nhlt as binary in nhlt.bin
saving nhlt as binary in nhlt.bin
[  1%] Built target abi_v1
find_modes(): fs not set
[  1%] Built target topology2_cavs-passthrough-hdmi
find_modes(): fs not set
[  1%] Built target topology2_cavs-sdw
[  1%] Built target topology2_cavs-mixin-mixout-hda
[  1%] Built target topology2_sof-mtl-nocodec
[  1%] Built target topology2_cavs-mixin-mixout-hda-2ch-tgl
saving nhlt as binary in nhlt-cavs-tgl-nocodec.bin
saving nhlt as binary in nhlt.bin
[  1%] Built target topology2_cavs-mixin-mixout-hda-2ch-cnl
[  1%] Built target topology2_cavs-mixin-mixout-hda-4ch-cnl
[  1%] Built target topology2_cavs-tgl-nocodec
[  1%] Built target topology2_cavs-mixin-mixout-hda-4ch-tgl
[  1%] Generating sof-hda-generic-3ch.conf
[  1%] Generating sof-hda-generic-2ch.conf
[  1%] Generating sof-adl-rt711.conf
[  1%] Generating sof-icl-rt700.conf
[  1%] Generating sof-icl-rt700-4ch.conf
[  1%] Generating sof-icl-rt700-2ch.conf
[  1%] Generating sof-hda-generic.conf
[  1%] Generating sof-cml-rt700-4ch.conf
[  1%] Generating sof-cml-rt700-2ch.conf
[  1%] Generating sof-hda-generic-4ch.conf
[  1%] Generating sof-hda-generic-1ch.conf
[  1%] Generating sof-cml-rt711-rt1308-mono-rt715.conf
[  1%] Generating sof-icl-rt711-rt1308-rt715.conf
[  1%] Generating sof-tgl-rt711-rt1308-mono-rt715.conf
[  1%] Generating sof-cml-rt700.conf
[  1%] Generating sof-cml-rt711-rt1308-rt715.conf
[  1%] Generating sof-tgl-rt715-rt711-rt1308-mono.conf
[  1%] Generating sof-adl-rt711-l2-rt1316-l01-rt714-l3.conf
[  1%] Generating sof-tgl-rt711-rt1308-rt715.conf
[  1%] Generating sof-adl-rt711-l0-rt1316-l13-rt714-l2.conf
[  1%] Generating sof-adl-rt711-l0-rt1316-l12-rt714-l3.conf
[  1%] Generating sof-tgl-rt711-rt1316-rt714.conf
[  1%] Generating sof-adl-rt711-l2-rt1316-l01.conf
[  1%] Generating sof-tgl-rt711-rt1308-4ch.conf
[  2%] Generating production/sof-byt-nocodec.conf
[  2%] Generating sof-adl-rt711-l0-rt1308-l12-rt715-l3.conf
[  2%] Generating production/sof-bdw-nocodec.conf
[  2%] Generating sof-tgl-rt711-rt1308-2ch.conf
[  2%] Generating sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.conf
[  2%] Generating production/sof-hda-generic-1ch.conf
[  2%] Generating sof-tgl-rt711-4ch.conf
[  2%] Generating sof-adl-rt711-4ch.conf
[  2%] Generating production/sof-hda-generic-2ch.conf
[  2%] Generating production/sof-cht-nocodec.conf
[  2%] Generating production/sof-hda-generic.conf
[  2%] Generating production/sof-hda-generic-3ch.conf
[  2%] Generating production/sof-hda-generic-idisp.conf
[  2%] Generating production/sof-hda-generic-idisp-2ch.conf
[  2%] Generating production/sof-hda-generic-idisp-4ch.conf
[  2%] Generating production/sof-hda-generic-4ch.conf
[  2%] Generating production/sof-apl-keyword-detect.conf
[  2%] Generating production/sof-bdw-rt5677.conf
[  3%] Generating production/sof-bdw-rt5640.conf
[  3%] Generating production/sof-bdw-rt286.conf
[  3%] Generating production/sof-byt-rt5640.conf
[  3%] Generating production/sof-byt-rt5670.conf
[  3%] Generating production/sof-byt-rt5651.conf
[  4%] Generating production/sof-byt-rt5645.conf
[  6%] Generating production/sof-byt-rt5682.conf
[  6%] Generating production/sof-byt-cx2072x.conf
[  7%] Generating production/sof-byt-es8316.conf
[  7%] Generating production/sof-byt-rt5640-ssp0.conf
[  8%] Generating production/sof-byt-rt5651-ssp0.conf
[  8%] Generating production/sof-byt-da7213.conf
[  8%] Generating production/sof-bdw-nocodec.tplg
[  8%] Generating production/sof-byt-rt5645-ssp0.conf
[  8%] Generating production/sof-byt-nocodec.tplg
[  8%] Generating production/sof-byt-rt5670-ssp0.conf
[  8%] Generating sof-hda-generic.tplg
[  8%] Generating production/sof-byt-rt5682-ssp0.conf
[  8%] Generating production/sof-byt-da7213-ssp0.conf
[  8%] Generating production/sof-byt-es8316-ssp0.conf
[  8%] Generating production/sof-byt-wm5102-ssp0.conf
[  9%] Generating production/sof-byt-cx2072x-ssp0.conf
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[  9%] Generating production/sof-cht-rt5645.conf
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 11%] Generating production/sof-cht-rt5640.conf
[ 12%] Generating production/sof-cht-rt5670.conf
[ 12%] Generating production/sof-cht-rt5651.conf
[ 12%] Generating production/sof-cht-nocodec.tplg
[ 12%] Generating production/sof-cht-rt5682.conf
[ 12%] Generating production/sof-cht-da7213.conf
[ 13%] Generating production/sof-cht-cx2072x.conf
[ 13%] Generating sof-hda-generic-3ch.tplg
[ 13%] Generating sof-icl-rt700-4ch.tplg
[ 13%] Generating sof-adl-rt711.tplg
[ 13%] Generating production/sof-cht-es8316.conf
Segmentation fault (core dumped)
[ 14%] Generating sof-icl-rt700-2ch.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-hda-generic.tplg] Error 139
[ 14%] Generating sof-cml-rt700-4ch.tplg
gmake[2]: *** [CMakeFiles/Makefile2:7825: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
[ 16%] Generating production/sof-cht-nau8824.conf
[ 16%] Generating sof-tgl-rt711-rt1308-mono-rt715.tplg
[ 16%] Generating sof-icl-rt700.tplg
[ 16%] Generating production/sof-hda-generic-idisp.tplg
[ 17%] Generating production/sof-cht-max98090.conf
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 17%] Generating production/sof-byt-max98090.conf
[ 18%] Generating production/sof-apl-keyword-detect.tplg
[ 18%] Generating production/sof-apl-tdf8532.conf
[ 18%] Generating sof-hda-generic-4ch.tplg
[ 18%] Generating production/sof-cnl-rt274.conf
[ 18%] Generating sof-hda-generic-1ch.tplg
[ 18%] Generating sof-cml-rt700-2ch.tplg
[ 19%] Generating production/sof-apl-pcm512x-master.conf
[ 19%] Generating sof-cml-rt711-rt1308-mono-rt715.tplg
[ 19%] Generating production/sof-apl-pcm512x-master-44100.conf
[ 19%] Generating production/sof-apl-pcm512x.conf
[ 19%] Generating sof-cml-rt700.tplg
ALSA lib pcm.c:1477:(tplg_parse_hw_config) deprecated bclk value 'codec_master', use 'codec_provider
ALSA lib pcm.c:1529:(tplg_parse_hw_config) deprecated fsync value 'codec_master', use 'codec_provider'
ALSA lib pcm.c:1477:(tplg_parse_hw_config) deprecated bclk value 'codec_master', use 'codec_provider
ALSA lib pcm.c:1529:(tplg_parse_hw_config) deprecated fsync value 'codec_master', use 'codec_provider'
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 19%] Generating production/sof-apl-rt298.conf
Segmentation fault
[ 19%] Generating production/sof-hda-generic.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700-4ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-cml-rt700-4ch.tplg] Error 139
[ 20%] Generating sof-icl-rt711-rt1308-rt715.tplg
gmake[2]: *** [CMakeFiles/Makefile2:8059: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700-4ch.dir/all] Error 2
[ 20%] Generating production/sof-apl-demux-pcm512x.conf
[ 22%] Generating sof-hda-generic-2ch.tplg
[ 22%] Generating sof-cml-rt711-rt1308-rt715.tplg
[ 23%] Generating production/sof-bdw-rt5677.tplg
[ 23%] Generating production/sof-apl-wm8804.conf
[ 23%] Generating production/sof-bdw-rt286.tplg
[ 24%] Generating production/sof-bdw-rt5640.tplg
Segmentation fault (core dumped)
Segmentation fault (core dumped)
[ 24%] Generating sof-adl-rt711-l2-rt1316-l01.tplg
[ 24%] Generating sof-tgl-rt711-rt1308-rt715.tplg
Segmentation fault (core dumped)
gmake[3]: *** [topology/topology1/CMakeFiles/topology1_sof-apl-keyword-detect.dir/build.make:73: topology/topology1/production/sof-apl-keyword-detect.tplg] Error 139
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-3ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-hda-generic-3ch.tplg] Error 139
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700-4ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-icl-rt700-4ch.tplg] Error 139
gmake[2]: *** [CMakeFiles/Makefile2:1195: topology/topology1/CMakeFiles/topology1_sof-apl-keyword-detect.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:7903: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-3ch.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:7981: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700-4ch.dir/all] Error 2
[ 24%] Built target topology1_sof-bdw-nocodec
[ 28%] Generating production/sof-cml-da7219-max98390.conf
[ 28%] Generating production/sof-apl-da7219.conf
[ 28%] Generating sof-tgl-rt711-rt1316-rt714.tplg
Segmentation fault (core dumped)
[ 28%] Generating sof-tgl-rt715-rt711-rt1308-mono.tplg
[ 28%] Built target topology1_sof-byt-nocodec
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-icl-rt700.tplg] Error 139
[ 28%] Generating sof-adl-rt711-l2-rt1316-l01-rt714-l3.tplg
[ 28%] Generating production/sof-glk-da7219-kwd.conf
gmake[2]: *** [CMakeFiles/Makefile2:7955: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700.dir/all] Error 2
[ 28%] Generating production/sof-hda-generic-idisp-2ch.tplg
[ 28%] Generating sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg
[ 28%] Generating production/sof-cml-da7219-max98357a.conf
[ 28%] Generating sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg
[ 29%] Generating production/sof-hda-generic-idisp-4ch.tplg
[ 29%] Generating production/sof-glk-da7219.conf
Segmentation fault (core dumped)
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700-2ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-icl-rt700-2ch.tplg] Error 139
[ 29%] Generating production/sof-glk-cs42l42.conf
[ 29%] Generating production/sof-glk-rt5682.conf
gmake[2]: *** [CMakeFiles/Makefile2:8007: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt700-2ch.dir/all] Error 2
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 30%] Generating production/sof-hda-generic-1ch.tplg
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
Segmentation fault
Segmentation fault (core dumped)
[ 30%] Generating production/sof-byt-rt5651.tplg
Segmentation fault (core dumped)
Segmentation fault (core dumped)
[ 30%] Generating production/sof-byt-rt5640.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-tgl-rt711-rt1308-mono-rt715.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-tgl-rt711-rt1308-mono-rt715.tplg] Error 139
gmake[3]: *** [topology/topology1/CMakeFiles/topology1_sof-hda-generic.dir/build.make:73: topology/topology1/production/sof-hda-generic.tplg] Error 139
[ 32%] Generating production/sof-apl-nocodec.conf
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt711-rt1308-rt715.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-icl-rt711-rt1308-rt715.tplg] Error 139
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-4ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-hda-generic-4ch.tplg] Error 139
[ 32%] Generating production/sof-hda-generic-2ch.tplg
[ 32%] Generating sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg
[ 32%] Generating production/sof-byt-rt5645.tplg
[ 32%] Generating production/sof-byt-rt5682.tplg
Segmentation fault (core dumped)
Segmentation fault (core dumped)
[ 32%] Generating production/sof-byt-rt5670.tplg
gmake[2]: *** [CMakeFiles/Makefile2:8163: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-icl-rt711-rt1308-rt715.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:7929: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-4ch.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:8189: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-tgl-rt711-rt1308-mono-rt715.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:987: topology/topology1/CMakeFiles/topology1_sof-hda-generic.dir/all] Error 2
[ 32%] Generating production/sof-glk-nocodec.conf
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt711-rt1308-mono-rt715.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-cml-rt711-rt1308-mono-rt715.tplg] Error 139
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700-2ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-cml-rt700-2ch.tplg] Error 139
[ 32%] Generating production/sof-cnl-nocodec.conf
[ 33%] Generating production/sof-cml-nocodec.conf
[ 33%] Generating production/sof-icl-nocodec.conf
Segmentation fault (core dumped)
gmake[2]: *** [CMakeFiles/Makefile2:8085: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700-2ch.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:8111: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt711-rt1308-mono-rt715.dir/all] Error 2
[ 33%] Generating production/sof-jsl-nocodec.conf
[ 34%] Generating sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-cml-rt700.tplg] Error 139
[ 34%] Built target topology1_sof-cht-nocodec
gmake[2]: *** [CMakeFiles/Makefile2:8033: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt700.dir/all] Error 2
[ 34%] Generating production/sof-byt-cx2072x.tplg
[ 34%] Generating production/sof-tgl-nocodec.conf
[ 34%] Generating production/sof-tgl-h-nocodec.conf
[ 34%] Generating production/sof-byt-es8316.tplg
Segmentation fault (core dumped)
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-1ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-hda-generic-1ch.tplg] Error 139
[ 35%] Generating sof-tgl-rt711-4ch.tplg
[ 35%] Built target topology1_sof-hda-generic-idisp
[ 35%] Generating production/sof-hda-generic-3ch.tplg
Segmentation fault (core dumped)
[ 35%] Built target topology_sof-adl-rt711
[ 35%] Generating production/sof-byt-rt5640-ssp0.tplg
gmake[2]: *** [CMakeFiles/Makefile2:7851: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-1ch.dir/all] Error 2
[ 35%] Generating sof-tgl-rt711-rt1308-2ch.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt711-rt1308-rt715.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-cml-rt711-rt1308-rt715.tplg] Error 139
Segmentation fault (core dumped)
[ 35%] Generating production/sof-byt-rt5651-ssp0.tplg
[ 35%] Generating production/sof-byt-da7213.tplg
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-2ch.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-hda-generic-2ch.tplg] Error 139
[ 35%] Generating production/sof-byt-rt5670-ssp0.tplg
gmake[2]: *** [CMakeFiles/Makefile2:8137: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-cml-rt711-rt1308-rt715.dir/all] Error 2
[ 37%] Generating sof-tgl-rt711-rt1308-4ch.tplg
gmake[2]: *** [CMakeFiles/Makefile2:7877: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-hda-generic-2ch.dir/all] Error 2
[ 37%] Generating production/sof-byt-rt5645-ssp0.tplg
Segmentation fault (core dumped)
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-tgl-rt711-rt1308-rt715.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-tgl-rt711-rt1308-rt715.tplg] Error 139
Segmentation fault (core dumped)
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 37%] Generating production/sof-byt-es8316-ssp0.tplg
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
gmake[3]: *** [topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-adl-rt711-l2-rt1316-l01.dir/build.make:73: topology/topology1/kernel_dependent/v5.19/sof-adl-rt711-l2-rt1316-l01.tplg] Error 139
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
gmake[2]: *** [CMakeFiles/Makefile2:8267: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-tgl-rt711-rt1308-rt715.dir/all] Error 2
[ 37%] Generating production/sof-byt-da7213-ssp0.tplg
[ 37%] Generating production/sof-ehl-nocodec.conf
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 38%] Generating production/sof-icl-dmic-4ch.conf
[ 38%] Generating production/sof-hda-generic-4ch.tplg
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
[ 38%] Generating production/sof-byt-rt5682-ssp0.tplg
gmake[2]: *** [CMakeFiles/Makefile2:8423: topology/topology1/kernel_dependent/v5.19/CMakeFiles/topology_sof-adl-rt711-l2-rt1316-l01.dir/all] Error 2
[ 39%] Generating production/sof-adl-nocodec.conf
[ 39%] Generating production/sof-byt-cx2072x-ssp0.tplg
[ 39%] Generating production/sof-byt-wm5102-ssp0.tplg
ALSA lib pcm.c:1471:(tplg_parse_hw_config) deprecated bclk value 'codec_slave', use 'codec_consumer'
ALSA lib pcm.c:1523:(tplg_parse_hw_config) deprecated fsync value 'codec_slave', use 'codec_consumer'
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
```

**Comment by lgirdwood** [comment]
@juimonen @ranj063 any ideas - looks like a topology compiler crash.
@Zames-Chang which topology file - the build output is in parallel so difficult to see which topology file is crashing the compiler ?

**Comment by juimonen** [comment]
@perexg FYI, something in latest alsa-lib head is segfaulting all our topology1 builds....

I see the segfault as:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ee20d7 in snd_interval_empty (i=<optimized out>) at /home/juimonen/work/alsa-lib/src/pcm/interval_inline.h:47
47		return i->empty;
(gdb) bt
#0  0x00007ffff7ee20d7 in snd_interval_empty (i=<optimized out>) at /home/juimonen/work/alsa-lib/src/pcm/interval_inline.h:47
#1  snd1_pcm_hw_param_get (params=0x0, var=var@entry=10, val=val@entry=0x7fffffffda2c, dir=dir@entry=0x0) at pcm_params.c:144
#2  0x00007ffff7edc57f in __snd_pcm_hw_params_get_channels (params=<optimized out>, val=val@entry=0x7fffffffda2c) at pcm.c:4492
#3  0x00007ffff7edfd8e in __old_snd_pcm_hw_params_get_channels (params=<optimized out>) at pcm.c:7885
#4  0x00007ffff7f88040 in parse_access_values (hdr=0x4b45e0, cfg=0x45d300) at ctl.c:78
#5  parse_access (cfg=cfg@entry=0x45cc50, hdr=hdr@entry=0x4b45e0) at ctl.c:99
#6  0x00007ffff7f88bb6 in tplg_parse_control_bytes (tplg=tplg@entry=0x4282f0, cfg=cfg@entry=0x45cc50, private=private@entry=0x0) at ctl.c:543
#7  0x00007ffff7f86902 in tplg_parse_compound (tplg=tplg@entry=0x4282f0, cfg=cfg@entry=0x45cbe0, fcn=0x7ffff7f88800 <tplg_parse_control_bytes>, private=private@entry=0x0) at parser.c:138
#8  0x00007ffff7f86bc4 in tplg_parse_config (cfg=0x43bb90, tplg=0x4282f0) at parser.c:186

and this lead me to commit 78b20e3caa7bba930095e05f, which does seems little fishy, at least what reads in the commit message.

But even after using the get_access method I still get segfault. So something perhaps in the ALSA_PCM_OLD_HW_PARAMS_API things, but not sure...

**Comment by juimonen** [comment]
@perexg thanks! builds now.

@Zames-Chang update alsa-lib to latest head.

**Comment by lgirdwood** [comment]
@Zames-Chang can we close ?

**Comment by Zames-Chang** [comment]
Hi 

Sorry for late reply. I can build topology now with latest head. Thanks for the help.
