### ISSUE TITLE
tools/coredumper: crashes with NameError: name 'fg' is not defined

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#945]
Only tested on ubuntu 18.04 / 18.10

```
root@up2:~# ./sof-coredump-reader.py 
Traceback (most recent call last):
  File "./sof-coredump-reader.py", line 241, in <module>
    class Colourer():
  File "./sof-coredump-reader.py", line 247, in Colourer
    'o' : fg.red,
NameError: name 'fg' is not defined
```

**Comment by abonislawski** [comment]
Fixed in PR #1186
